# name: CD Pipeline

# on:
#   workflow_run:
#     workflows: ["CI Pipeline"]
#     types:
#       - completed

# jobs:
#   build:
#     runs-on: self_hosted

#     steps:
#       - name: Pull Docker Image
#         run: sudo docker pull christianog/actions_test:latest
#       - name: Delete old docker container
#         run: sudo docker rm -f actions || true
#       - name: Run docker container
#         run : sudo docker run -d -p 3005:3005 --name actions christianog/actions_test:latest
